version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - database-data:/var/lib/postgresql/data/
    user: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    build: .
    command: bundle exec unicorn -p ${WEB_PORT} -E production -c config/unicorn.rb
    volumes:
      - .:/app
    environment:
      RACK_ENV: ${APP_ENV} 
      RAILS_ENV: ${APP_ENV}  
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - db

volumes:
    database-data: 